version: '3'
services:
  frontend:
    build:
      context: frontend  # Builds from the current directory
      dockerfile: Dockerfile  # Path to the Dockerfile for the frontend
    ports:
      - "5500:5500"  # Maps port 80 in the container to port 80 on the host
    depends_on:
      - backend

  backend:
    build:
      context: backend  # Builds from the current directory
      dockerfile: Dockerfile  # Path to the Dockerfile for the backend
    ports:
      - "8080:8080"  # Maps port 4242 in the container to port 4242 on the host
    depends_on:
      - db
    environment:
      SEQ_DB: postgres
      SEQ_USER: postgres0
      SEQ_PW: qw12
      PORT: 8080
      DATABASE_URL: postgres://postgres:qw12@db:5432/postgres

  db:
    image: postgres
    ports:
      - "32768:5432"
    environment:
      POSTGRES_USER: postgres0
      POSTGRES_PASSWORD: qw12
      POSTGRES_DB: postgres
